var quotes = [
["A set of all sets!", "Russel's Paradox"],
["The favicon is a PNG!"],
["Black screens save power!"],
["A gramme is better than a damn!", "A Brave New World, by Aldous Huxely"],
//["240x300 tested!"],
["Variety is the spice of life!"],
["Now worth [UNDEFINED] US dollars!", "Uninitialized variables in JavaScript are of type \"undefined\"."],
["Microsoft Edge COULD be considered a modern browser!"],
["Guess who?!", "This is an imperative. It should end in a period. That's the joke."],
["Help, I'm stuck in a randomly-generated JavaScript phrase factory!"],
["...has seen enough hentai to know where this is going!", "Reference to the \"Seen Enough Hentai\" meme"],
["Users of IE 9 and under just have to suck it up!"],
["Ha ha! Hello!", "Quote from some dumb YouTube video."],
["The catch is, you can only choose one!", "/r9k/ saying, coupled with a scenario with two equally good outcomes the poster must choose between."],
["And to think, all it took was a !DOCTYPE!", "HTML5's !DOCTYPE is simply \"<!DOCTYPE html>\""],
["I could make it XHTML if I wanted to, but XHTML's dead anyway!"],
["Oceania has always been at war with Eastasia!", "1984, by George Orwell"],
["But tonight, it's heavy stuff!", "Pendulum - Slam"],
["It's people! JavaScript is made of people!", "Reference to the infamous \"Soylent Green\" scene"],
["Murdertime, funtime!", "Saints Row The Third - Professor Genki's Super Ethical Reality Climax"],
["I'm the strongest!", "Touhou - Cirno catchphrase"],
["Work hard, die young, win valuable prizes!", "from a monitor in Oddworld: Abe's Oddysee"],
["I'm your number one fan!"],
["Subculture was cooler when it was mixed by Dieselboy and Kaos!"],
["ASK ME ABOUT MY WEINAAAA", "I asked a friend if he wanted to add a quote once. Thanks Luke."],
["That's what &lt;span&gt; is for!", "<a> is used for links only now."],
["Exclamation point!"],
["&quot;Anyway, the point is, my opinion is better.&quot; ~The wisdom of c4g!"],
["They'll sew their own hands into their beds to keep them Crawlersout!", "Purity Ring - Crawlersout"],
["EOL'd in Windows format!"],
["PHP is easier than I expected!"],
["Mmmmmmmm, gulp!", "Homestar Runner - Cheat Commandos 2 Part Episode Part 2"],
["Ooh, 98 SE-tan! Ooh!", "Reference to the Windows-tans and \"Ooh, Mister Darcy: A Fantiction\"."],
["Phrases generated while you wait!", "\"[Something done] while you wait\" is a common service-shop phrase."],
["Hola chica, hago videojuegas!", "Old GG2 Forum saying, translated to Spanish."],
["Imagine, if you will...!", "Common introductory phrase from The Twilight Zone"],
["Today is Aug. 5th, 2026!", "There Will Come Soft Rains / The Martian Chronicals, Ray Bradbury"],
["Tower of Daruga got sequels in Japan and I'm really mad about that!", "This is true! Tower of Daruga spawned a whole series of merch... but only in Japan."],
["Bring us the girl, and wipe away the debt!", "Bioshock Infinite"],
["Check out the &quot;More Phrases&quot; DLC pack available for 12.11 BTC or Dogecoin!", "This is a jab at 1) DLC, and 2) Virtual Currency."],
["Hey, I actually <i>liked</i> James Cameron's AVATAR!"],
["Who's that man with the three piece suit?!", "Octodad."],
["They don't pay me <i>near</i> enough to call the cops at 3 A.M. and report a tire-jacking by a walrus!", "I don't remember where this reference is from."],
["Look elsewhere, <a href='http:// twitter.com/h00die96'>@h00die96</a>! Maybe I'm not here!", "CAVE! CAVE! DEUS VIDET."],
["Quotes for the quote god! JavaScript for the JavaScript throne!", "Warhammer 40,000 (specifically, Khorne)"],
["I am a skeleton with standards!", "Undertale"],
["You are huge! That means you have huge guts!", "DOOM comic"],
["Chainsaw! The Great Communicator!", "DOOM comic"],
["Here comes the night train!", "DOOM comic"],
["But I didn't die, though, it was a joke!", "JonTron"],
["It takes two to tango, but, boy, it's one to let go!", "The Wallflowers - Letters From The Wasteland"],
["The reason my molars are so broken, is I've spent too much time Ghosting with the likes of you and yours!", "Freelance Whales - Ghosting"],
["The reason my insides are so swollen, is I've spent too much time Ghosting with the likes of you and yours!", "Freelance Whales - Ghosting"],
["Another day, staring at the ceiling!", "Breathe - Telepopmusik"],
["Hey! We are a elephant! We love giraffes!", "Baths - Aminals"],
["It feels like a gun!", "Logan7 - Uptown Saturday Night"],
["In 2080 I'll surely be dead, so don't look ahead! Never look ahead!", "Yeasayer - 2080"],
["Yeah! Yeah! We can all grab at the chance to be handsome farmers!", "Yeasayer - 2080"],
["And the pain that we left at the station will stay in a jar behind us!", "Yeasayer - 2080"],
["You can find me, I'll be sitting by the water fountain!", "Yeasayer - 2080"],
["Being myself makes me feel like I can't hear the sound!", "Vowels = space and time - Grimes"],
["Is it amonesia?! Amanaemonesia?!", "Chairlift - Amanaemonesia"],
["Baby! Do you read me? I think these numbers are beginning to eat me!", "I Monster - Dear John"],
["I know Soho is just a parody of itself!", "The Correspondents - What's Happened To Soho?"],
["So long to this wretched form!", "The Shins - The Rifle's Spiral"],
["Damn grey eyes on the subway!", "The Shins - The Rifle's Spiral"],
["Rise! Rise from your burning Fiat!", "The Shins - The Rifle's Spiral"],
["You're not invisible now, you just don't exist!", "The Shins - The Rifle's Spiral"],
["Go back to this wretched form!", "The Shins - The Rifle's Spiral"],
["Ain't she lovely, bone and blood!", "The Shins - September"],
["I've been selfish, and full of pride!", "The Shins - September"],
["She knows, deep down, there's a little child!", "The Shins - September"],
["But I've got a good side to me as well!", "The Shins - September"],
["And it's that she loves in spite of everything else!", "The Shins - September"],
["It's not that the darkness can't touch our lives, I know it will in time!", "The Shins - September"],
["Under our softly burning lamp, she takes her time telling stories of our possible lives!", "The Shins - September"],
["It's not supposed to be easy! That's why it feels so f*cking good!", "AWOLNATION - Jump On My Shoulders"],
["No need to worry, 'cause everybody will die!", "AWOLNATION - Kill Your Heroes"],
["Don't you worry, we love you more than you know!", "AWOLNATION - Kill Your Heroes"],
["The sun, one day, will leave us all behind!", "AWOLNATION - Kill Your Heroes"],
["Never let your fears decide your fate!", "AWOLNATION - Kill Your Heroes"],
["Through the woods we ran!", "Of Monsters And Men - Mountain Sound"],
["And as I traveled on, I began to notice we were nothing like the rest!", "Of Monsters And Men - Mountain Sound"],
["Sleep until the sun goes down!", "Of Monsters And Men - Mountain Sound"],
["Deep into that mountain sound!", "Of Monsters And Men - Mountain Sound"],
["I heard them calling in the distance, so I packed my things and ran!", "Of Monsters And Men - Mountain Sound"],
["The birds, they got help from below, from Dirty Paws and the Creatures of Snow!", "Of Monsters And Men - Dirty Paws"],
["There's an old voice in my head that's holding me back! <span class=\"mini\">Well, tell her that I miss our little talks.</span>", "Of Monsters And Men - Little Talks"],
["Some days, I don't know if I am wrong or right! <span class=\"mini\">Your mind is playing tricks on you, my dear.</span>", "Of Monsters And Men - Little Talks"],
["Now wait! Wait! Wait for me! Please hang around! I'll see you when I fall asleep!", "Of Monsters And Men - Little Talks"],
["I'll see you when I fall asleep!", "Of Monsters And Men - Little Talks"],
["Just grab ahold of my hand. I will lead you through this wonderland!", "Of Monsters And Men - Yellow Light"],
["Just follow my yellow light, and ignore all those big warning signs!", "Of Monsters And Men - Yellow Light"],
["If you're fond of sand dunes and salty air!", "Groove Armada - At The River"],
["Get used to the dust in your lungs!", "The Shins - No Way Down"],
["Apologies to the sick and the young!", "The Shins - No Way Down"],
["Make me a drink strong enough to wash away the dishwater world they said was lemonade!", "The Shins - No Way Down"],
["How'd we get so far from the sun?!", "The Shins - No Way Down"],
["Lost! Lost in an oscillating phase where a tiny few catch all of the rays!", "The Shins - No Way Down"],
["Is there no way down from this peak to solid ground without having our gold teeth pulled from our mouth?!", "The Shins - No Way Down"],
["It's just that I'm afraid I'll slide under that spell again!", "The Shins - For A Fool"],
["Yes, I was because I was a fool!", "The Shins - For A Fool"],
["If I can learn anything from this, then I'd be like the fox in the fable!", "The Shins - For A Fool"],
["And you were right, so I'm thanking you!", "The Shins - Fall Of '82"],
["Are you gonna let these Americans put another dent in your life?!", "The Shins - 40 Mark Strasse"],
["Under my hat, it reads \"The lines are all imagined!\"", "The Shins - Port Of Morrow"],
["See, those unrepenting buzzards want your life, and they got no right!", "The Shins - Sleeping Lessons"],
["Every post you can hitch your faith on is a pie in the sky!", "The Shins - A Comet Appears"],
["Goodbye stranger! It's been nice!", "Supertramp - Goodbye Stranger"],
["There are rainbows, and earthworms, and microscopic hummingbirds!", "Black Moth Super Rainbow - I Think It Is Beautiful That You Are 256 Colors Too"],
["I'll shuck all the light from my skin and I'll hide it in you!", "Purity Ring - Shuck"],
["Only, lonely, hidden breath beneath the floor!", "Purity Ring - heartsigh"],
["Only, only, where your tears drip from the drawers!", "Purity Ring - heartsigh"],
["Only, lonely, hid the morning from the stars!", "Purity Ring - heartsigh"],
["Only, only, weeping glimmers in the dark!", "Purity Ring - heartsigh"],
["Carry on, wearily or not!", "Purity Ring - heartsigh"],
["Oh, glasses clinking, and a new order's blinking!", "Animal Collective - What Would I Want? Sky"],
["Overall, I cannot accuse a dead man of murder!", "Nature of Nature's Art, \"10%+\", page 222"],
["We talk with the body! Words don't mean anything anymore!", "Nature of Nature's Art, \"Secretary\", page 214"],
["<i>I am dying. I think she told me this in her own way.</i>", "Nature of Nature's Art, \"Secretary\", page 290"],
["The story must be told!", "Nature of Nature's Art, \"Secretary\", page 291"]
];

var quote = document.getElementById("quote");
var quotenum = Math.floor(Math.random()*(quotes.length));

quote.innerHTML = quotes[quotenum][0];

if (quotes[quotenum[1]]){
    quote.title = quotes[quotenum][1];
}
else {
    quote.title = undefined;
}
