// ["The favicon is a PNG!"],
// ["240x300 tested!"],
// ["Variety is the spice of life"],
// ["Now worth [UNDEFINED] US dollars!", "Uninitialized variables in JavaScript are of type \"undefined\"."],
// ["Microsoft Edge COULD be considered a modern browser!"],
// ["Help, I'm stuck in a randomly-generated JavaScript phrase factory!"],
// ["...has seen enough hentai to know where this is going!", "Reference to the \"Seen Enough Hentai\" meme"],
// ["Users of IE 9 and under just have to suck it up!"],
// ["Ha ha! Hello!", "Quote from some dumb YouTube video."],
// ["The catch is, you can only choose one!", "/r9k/ saying, coupled with a scenario with two equally good outcomes the poster must choose between."],
// ["And to think, all it took was a !DOCTYPE!", "HTML5's !DOCTYPE is simply \"<!DOCTYPE html>\""],
// ["I could make it XHTML if I wanted to, but XHTML's dead anyway!"],
// ["It's people! JavaScript is made of people!", "Reference to the infamous \"Soylent Green\" scene"],
// ["I'm your number one fan!"],
// ["Subculture was cooler when it was mixed by Dieselboy and Kaos!"],
// ["ASK ME ABOUT MY WEINAAAA", "I asked a friend if he wanted to add a quote once. Thanks Luke."],
// ["That's what &lt;span&gt; is for!", "<a> is used for links only now."],
// ["Exclamation point!"],
// ["&quot;Anyway, the point is, my opinion is better.&quot; ~The wisdom of c4g!"],
// ["PHP is easier than I expected!"],
// ["Ooh, 98 SE-tan! Ooh!", "Reference to the Windows-tans and \"Ooh, Mister Darcy: A Fantiction\"."],
// ["Phrases generated while you wait!", "\"[Something done] while you wait\" is a common service-shop phrase."],
// ["Tower of Daruga got sequels in Japan and I'm really mad about that!", "This is true! Tower of Daruga spawned a whole series of merch... but only in Japan."],
// ["Check out the &quot;More Phrases&quot; DLC pack available for 12.11 BTC or Dogecoin!", "This is a jab at 1) DLC, and 2) Virtual Currency."],
// ["Hey, I actually <i>liked</i> James Cameron's AVATAR!"],
// ["They don't pay me <i>near</i> enough to call the cops at 3 A.M. and report a tire-jacking by a walrus!", "I don't remember where this reference is from."],
// ["The birds, they got help from below, from Dirty Paws and the Creatures of Snow", "Of Monsters And Men - Dirty Paws"],
